### ISSUE TITLE
General refactoring

### ISSUE THREAD

**Issue by christopherfrige** [christopherfrige/league-player-searcher#1]
All the code is in a .py file.

**TODO:**
- [x] Apply SOLID in the functions. 
- [x] Modularize the program.
- [x] Riot API Token in env variables
- [x] More description on README (requirements, configuring, run)

**Comment by christopherfrige** [comment]
Tópico "Apply SOLID in the functions" concluído com o PR #2

**Comment by christopherfrige** [comment]
O tópico **Modularize the program** foi concluído com o PR #3

**Comment by christopherfrige** [comment]
Tõpico **Riot API Token in env variables** concluído por meio de um commit.

**Comment by christopherfrige** [comment]
O item **More description on README** foi concluído após o Merge do PR #4 
Todos os itens foram concluídos, issue será fechada.
